apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dtc-azure-kvsync
  namespace: dtc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: '10cca5dd-9908-44d7-9607-ea17c16cd0fe' 
    keyvaultName: "kv-gktsxdtw62iiq"
    cloudName: ""
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"
    objects:  |
      array:
        - |
          objectName: appinsightssecret
          objectType: secret    # object types: secret, key, or cert
          objectVersion: ""     # default to latest if empty
        - |
          objectName: mailserveruser
          objectType: secret    # object types: secret, key, or cert
          objectVersion: ""     # default to latest if empty
        - |
          objectName: mailserverpassword
          objectType: secret    # object types: secret, key, or cert
          objectVersion: ""     # default to latest if empty                             
  secretObjects:                              
    - secretName: appinsightssecret
      type: Opaque
      data:
      - key: appinsights-connection-string                           
        objectName: appinsightssecret                        
    - secretName: mailserveruser
      type: Opaque
      data: 
      - key: smtp.user                           
        objectName: mailserveruser
    - secretName: mailserverpassword
      type: Opaque
      data:    
      - key: smtp.password                           
        objectName: mailserverpassword
                          