apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
    version: v1
  name: mosquitto
  namespace: dapr-trafficcontrol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: acrdtctye.azurecr.io/mosquitto:v1
          imagePullPolicy: Never
          ports:
          - containerPort: 1883
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: dapr-trafficcontrol
spec:
  ports:
  - name: "mqtt"
    port: 1883
    targetPort: 1883
  selector:
    app: mosquitto
