apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
  namespace: dtc
  labels:
    app: simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: acrdtc1231.azurecr.io/simulation:v4
        env:
          - name: MQTT_HOST
            value: mosquitto
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: app-env-secret  # Matches your secret name
                key: appinsights-connection-string  # matches the key of the secret data  
