apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simulation
    version: v1
  name: simulation
  namespace: dtc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulation
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      - name: simulation
        image: acrdtc1231.azurecr.io/dtc/simulation:v1
        imagePullPolicy: Always
        env:
          - name: MQTT_HOST
            value: mosquitto
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: app-env-secret  # Matches your secret name
                key: appinsights-connection-string  # matches the key of the secret data  
        restartPolicy: Always        
