apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficcontrolservice
  namespace: dtc
  labels:
    app: trafficcontrolservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trafficcontrolservice
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: trafficcontrolservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "trafficcontrolservice"
        dapr.io/app-port: "6000"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: trafficcontrolservice
        image: acrdtc1231.azurecr.io/dtc/trafficcontrolservice:v1
        imagePullPolicy: Always
        env:
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: app-env-secret  # Matches your secret name
                key: appinsights-connection-string  # matches the key of the secret data
          # - name: ASPNETCORE_URLS 
          #   value: "http://*:6000"      
        ports:
          - containerPort: 6000
      restartPolicy: Always      