apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub
  namespace: dtc
spec:
  topic: speedingviolations
  routes: 
    default: /collectfine
  pubsubname: pubsub
scopes:
  - trafficcontrolservice
  - finecollectionservice