apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dtc
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: namespaceName
    value: "amqp://rabbitmq:5672"
  - name: consumerID
    value: "false"
scopes:
  - trafficcontrolservice
  - finecollectionservice