apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailserver
    version: v1
  name: mailserver
  namespace: dtc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
      version: v1
  template:
    metadata:
      labels:
        app: mailserver
        version: v1
    spec:
      containers:
      - image: maildev/maildev:2.0.5 
        imagePullPolicy: IfNotPresent
        name: mailserver
        ports:
        - containerPort: 1025
        - containerPort: 1080
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailserver
    version: v1
  name: mailserver
  namespace: dtc
spec:
  type: LoadBalancer
  ports:
  - name: "smtp"
    port: 25
    targetPort: 1025
  - name: "web"
    port: 4000
    targetPort: 1080
  selector:
    app: mailserver
    version: v1
