apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-appinsights
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # true since using managed identity
    userAssignedIdentityID: "0890dec0-8912-487e-8ad7-34671c5f5a7b"
    keyvaultName: "kv-ilc2pjk7h3m5u"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: appinsights-secret
          objectType: secret    # object types: secret, key, or cert
          objectVersion: ""     # default to latest if empty
    tenantId: "16b3c013-d300-468d-ac64-7eda0820b6d3"