apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
    version: v1
  name: rabbitmq
  namespace: dtc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: prometheus
              containerPort: 15692
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: dtc
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: 15692
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672  
  selector:
    app: rabbitmq
