name: build_tag_deploy_aks

on:
  # Triggers the workflow on pull request events but only for the main branch
  # pull_request:
  #   branches: [main]
  #   types: [closed]
    push:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        id: login
        uses: azure/login@1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}