name: build_tag_deploy_aks

on:
  # Triggers the workflow on pull request events but only for the main branch
  # pull_request:
  #   branches: [main]
  #   types: [closed]
    push:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Azure login
        id: login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}